---
title: "MXNet CPU installation in R - Manjaro Linux/Archlinux"
output: rmarkdown::github_document
---

Document references:
- [MXNet Getting started](https://mxnet.incubator.apache.org/get_started/install.html)

This document provides instructions on how to install MXNet for R on CPU mode 
for Manjaro or Archlinux based systems. It can be extrapolated to other linux 
distros, however the commands will vary. 

TODO: 

- Create guide for Ubuntu.
- Create guide for Windows.

```{bash}
yaourt -S openblas-lapack
sudo pacman -S opencv
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.
